# Generated by Django 4.0.1 on 2022-01-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/default_image.jpeg', upload_to='product'),
        ),
    ]
