# Generated by Django 4.0.1 on 2022-01-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Movie',
        ),
    ]
